// Sample library
var mt_lib = [
  {w: "Cheers", r: "Kampai"},
  {w: "Hello", r: "bello"},
  {w: "Goodbye", r: "poopayo"},
  {w: "Ice cream", r: "gelato"},
  {w: "Thank you", r: "tank yu"},
  {w: "I'm sorry", r: "bi do"},
  {w: "Fire", r: "be do be do be do"},
  {w: "Bottom", r: "buttom"},
  {w: "1,2,3", r: "hana, dul, sae"},
  {w: "Chair", r: "chasy "},
  {w: "Marriage", r: "la boda"},
  {w: "Butt", r: "butt"},
  {w: "Banana", r: "banana"},
  {w: "Apple", r: "bable"},
  {w: "I'm hungry", r: "me want banana"},
  {w: "I hate you", r: "tatata bula tu"},
  {w: "I love you", r: "tulaliloo ti amo"},
  {w: "I swear", r: "underwear"},
  {w: "I love you", r: "me ti amo"},
  {w: "What", r: "po ka"},
  {w: "Toy", r: "papoy "},
  {w: "Kiss kiss", r: "Muak muak muak"}
];